name: Generate Contribution Snake

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG files
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Hamza-Hmidani
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-light
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit updated snake files
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/github-contribution-grid-snake.svg output/github-contribution-grid-snake-dark.svg"
          message: "chore: update contribution snake"
